[build]
  command = "npm run build"
  publish = "dist/"

[template]
  incoming-hooks = ["Ghost"]
  
  # These rules will change if you change your site’s custom domains or HTTPS settings

Redirect default Netlify subdomain to primary domain
https://blissful-archimedes-cc07d9.netlify.com/* https://noche.eu.org/:splat 301!
